<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class StockMovement extends Model
{
    //
    const TRANSACTION_TYPE_IN = 0;

    const TRANSACTION_TYPE_OUT = 1;

    const REFERENCE_TYPE_BRANCH_STOCK_TRANSFER = 0;

    const REFERENCE_TYPE_SHOP_STOCK_TRANSFER = 1;

    const REFERENCE_TYPE_CENTRAL_WAREHOUSE_STOCK_TRANSFER = 2;

    const REFERENCE_TYPE_CENTRAL_WAREHOUSE_PURCHASE = 3;

    const REFERENCE_TYPE_SHOP_SALE_OUT = 4;

    const REFERENCE_TYPE_SHOP_SALE_RETURN = 5;

    const REFERENCE_TYPE_SHOP_STOCK_ADJUSTMENT = 6;

    const REFERENCE_TYPE_BRANCH_STOCK_ADJUSTMENT = 7;

    const REFERENCE_TYPE_CENTRAL_WAREHOUSE_STOCK_ADJUSTMENT = 8;

    const REFERENCE_TYPE_BRANCH_INCOMING_DELIVERY_NOTE = 9;

    const REFERENCE_TYPE_SHOP_INCOMING_DELIVERY_NOTE = 10;

    const APPROVAL_STATUS_PENDING = 0;

    const APPROVAL_STATUS_APPROVED = 1;

    const APPROVAL_STATUS_REJECTED = 2;
}
