# .github/workflows/deploy.yml
name: Laravel CI & Deploy

on:
  push:
    branches:
      - main

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run Laravel Pint
        run: vendor/bin/pint --test --verbose
#to create  a test job to test the code with pint and only if it passes then run the deploy job
  test:
    runs-on: ubuntu-latest
    needs: pint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, dom, curl, libxml, sqlite, pdo_sqlite, bcmath
          tools: composer
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Unit Tests
        run: vendor/bin/phpunit --testsuite=Unit

      # Run Feature Tests (Database & Route tests)
      - name: Run Feature Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: vendor/bin/phpunit --testsuite=Feature


  deploy:
    runs-on: ubuntu-latest
    needs: test   # only run deploy if Pint passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/laravel-app   # adjust to your app path
            git pull origin main
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env
            echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # restart services if needed
            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx
          EOF
